### PR TITLE
MG-47 - Fix listing bug

### LINKED ISSUE #47: Bug: Docusaurus does not show lists
### What were you trying to achieve?

The Markdown files present numbered lists but these lists do not show up on the documentation.

### What are the expected results?

To be able to view numbered lists.

### What are the received results?

Block Statements show up instead of actual lists.

### In what environment did you encounter the issue?

On main branch website deployment.

### PR DESCRIPTION
**Pull request by Musilah**
Pull request title should be `MG-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?

This fixes the lists in the documentation 

### Which issue(s) does this PR fix/relate to?

Resolves #47 

### List any changes that modify/break current functionality

- [x] Added styles in global.css

### Have you included tests for your changes?
N/A
### Did you document any new/modified functionality?
N/A
### Notes
image

image

This is the React error on every component present: 
```js
'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.ts(2686)
(property) React.JSX.IntrinsicElements.div: React.DetailedHTMLProps<React.HTMLAttributes<HTMLDivElement>, HTMLDivElement>
```

### CODE REVIEW

**Comment by dborovcanin** [comment]
@Musilah Please rebase.

File: src/components/section-benefits.tsx [hunk 1]
```diff
@@ -24,6 +25,7 @@ export function BenefitsSection() {
 }
 
 interface Props {
+  key?: string;
```
Comment (ianmuchyri) [inline src/components/section-benefits.tsx:28]: The key isn't being used

File: src/components/section-features.tsx [hunk 2]
```diff
@@ -27,6 +28,7 @@ export function FeaturesSection() {
 }
 
 interface Props {
+  key?: string;
```
Comment (ianmuchyri) [inline src/components/section-features.tsx:31]: The key is also not being used here, remove it

File: src/components/section-use-for.tsx [hunk 3]
```diff
@@ -30,6 +31,7 @@ const icons = {
 function UsedForCard({
   usedFor,
 }: {
+  key?: string;
```
Comment (ianmuchyri) [inline src/components/section-use-for.tsx:34]: remove here as well

File: src/components/section-usecases.tsx [hunk 4]
```diff
@@ -40,6 +41,7 @@ export function UsecasesSection() {
 }
 
 interface Props {
+  key?: string;
```
Comment (ianmuchyri) [inline src/components/section-usecases.tsx:44]: remove here as well

**Review by ianmuchyri — CHANGES_REQUESTED** [review]

File: src/components/section-benefits.tsx (hunk 1 above)
Comment (Musilah) [reply src/components/section-benefits.tsx:28]: It is being used in the [Benefits](https://github.com/absmach/magistrala-docs/blob/main/src/components/section-benefits.tsx#L14) section just above.

File: tsconfig.json [hunk 5]
```diff
@@ -2,6 +2,7 @@
   // This file is not used in compilation. It is here just for a nice editor experience.
   "extends": "@docusaurus/tsconfig",
   "compilerOptions": {
+    "jsx": "react",
```
Comment (ianmuchyri) [inline tsconfig.json:5]:
```suggestion

```

File: src/lib/utils.ts [hunk 6]
```diff
@@ -1,5 +1,6 @@
 import { clsx, type ClassValue } from "clsx";
 import { twMerge } from "tailwind-merge";
+import React from "react";
```
Comment (ianmuchyri) [inline src/lib/utils.ts:3]:
```suggestion

```

File: src/components/section-usecases.tsx [hunk 7]
```diff
@@ -40,6 +40,7 @@ export function UsecasesSection() {
...
```
Comment (ianmuchyri) [inline src/components/section-usecases.tsx:43]:
```suggestion

```

File: src/components/section-use-for.tsx [hunk 8]
```diff
@@ -30,6 +30,7 @@ const icons = {
...
```
Comment (ianmuchyri) [inline src/components/section-use-for.tsx:33]:
```suggestion

```

File: src/components/section-pricing.tsx [hunk 9]
```diff
@@ -50,6 +50,7 @@ export function PricingSection() {
 }
 
 interface Props {
+  key?: string;
```
Comment (ianmuchyri) [inline src/components/section-pricing.tsx:53]:
```suggestion

```

File: src/components/section-features.tsx [hunk 10]
```diff
@@ -27,6 +27,7 @@ export function FeaturesSection() {
...
```
Comment (ianmuchyri) [inline src/components/section-features.tsx:30]:
```suggestion
 
```

**Review by ianmuchyri — CHANGES_REQUESTED** [review]

File: src/pages/index.tsx [hunk 11]
```diff
@@ -1,8 +1,8 @@
+import React from "react";
 import { HeroSection } from "../components/section-hero";
 import { TrustedBySection } from "../components/section-trusted-by";
 import { ProductSection } from "../components/section-product";
 import { BenefitsSection } from "../components/section-benefits";
-import { FeaturesSection } from "../components/section-features";
```
Comment (ianmuchyri) [inline src/pages/index.tsx:5]: Remove the commented out code for this as well

**Review by ianmuchyri — CHANGES_REQUESTED** [review]

**Review by ianmuchyri — APPROVED** [review]
